name: example_gen
description: A example generator for Dart objects with constraints.
version: 1.0.1
repository: https://github.com/lollipopkit/example_gen

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^6.0.0
  test: ^1.25.6
