name: example_gen
description: A example generator for Dart objects with constraints.
version: 1.0.0
repository: https://github.com/lollipopkit/example_gen

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^6.0.0
  test: ^1.25.6
